### ISSUE TITLE
Cant compile CentOS 7

### ISSUE THREAD

**Issue by acruzpr** [liedllab/gigist#1]
Im trying to compile your code but I get the following error after editing all necessary files:

cd src && make install
make[1]: Entering directory `/home/acruz/Development/gigist/cpptraj-18.00/src'
cd cuda_kernel_gist/ && make all
make[2]: Entering directory `/home/acruz/Development/gigist/cpptraj-18.00/src/cuda_kernel_gist'
/usr/local/cuda-9.2/bin/nvcc  -c -arch=sm_30  -lineinfo -o GistCudaCalc.o GistCudaCalc.cu
/usr/local/cuda-9.2/bin/nvcc  -c -arch=sm_30  -lineinfo -o GistCudaSetup.o GistCudaSetup.cu
GistCudaSetup.cuh(28): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

GistCudaSetup.cu(304): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

2 errors detected in the compilation of "/tmp/tmpxft_00007dab_00000000-6_GistCudaSetup.cpp1.ii".
make[2]: *** [GistCudaSetup.o] Error 1
make[2]: Leaving directory `/home/acruz/Development/gigist/cpptraj-18.00/src/cuda_kernel_gist'
make[1]: *** [cuda_kernel_gist/lib_cuda_gist.a] Error 2
make[1]: Leaving directory `/home/acruz/Development/gigist/cpptraj-18.00/src'
make: *** [install] Error 2

What could be the problem?

Could you share:
1) version of cpptraj that you are using
2) cuda version
3) gnu compilers version 

Here are mine:
 NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

cpptraj release 18

**Comment by jokr91** [comment]
Please check if the solution added on the compilationFix branch fixes this issue.
In general, the compilation problem stems from the fact that in C++11 you don't need to add spaces between closing brackets of nested templates, so
```cpp
vector<vector<float>>
```
would work in C++11, however in earlier C++ standards, one must use
```cpp
vector<vector<float> >
```
note the space between the closing brackets. These are necessary and I added them in the spirit of compatibility.
My commit should fix those problems.

Sorry for getting back to you so late, I missed the notification on this issue.

**Comment by acruzpr** [comment]
No Problem! 
Thanks! After your fix I was able to compile it.

Do you have a test set that I can use? because Im trying with the test files from the GIST test in cpptraj and Im getting the following error:

CPPTRAJ: Trajectory Analysis. V4.20.1 (GitHub) OpenMP CUDA
    ___  ___  ___  ___
     | \/ | \/ | \/ | 
    _|_/\_|_/\_|_/\_|_

| 12 OpenMP threads available.
| Date/time: 10/23/19 10:08:11
| Available memory: 1.690 GB
| CUDA device: GeForce RTX 2080
| Available GPU memory: 8.338 GB

INPUT: Reading input from 'gist.in'
  [parm ../../tz2.ortho.parm7]
        Reading '../../tz2.ortho.parm7' as Amber Topology
        Radius Set: modified Bondi radii (mbondi)
        This Amber topology does not include atomic numbers.
        Assigning elements from atom masses/names.
  [trajin ../../tz2.ortho.nc 1 10]
        Reading '../../tz2.ortho.nc' as Amber NetCDF
  [autoimage origin]
    AUTOIMAGE: To origin based on center of mass, anchor is first molecule.
  [gigist doorder refdens 0.033422885325 gridcntr 1.5 1.0 0.0 griddim 34 44 36 gridspacn 0.50 prefix Gist2 info Info.dat]
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: One or more grid sizes are 0: 1 1 0
Error: [gigist] Not all arguments handled: [ prefix Gist2 info Info.dat ]
        1 errors encountered reading input.
Warning: Set 'GIST_00001[population]' contains no data.
Warning: File 'population.dx' has no sets containing data.
TIME: Total execution time: 0.0960 seconds.
Error: Error(s) occurred during execution.

**Comment by jokr91** [comment]
Hi,
the new update should address this issue. I had a different order in the arguments than is used in the cpptraj GIST implementation. Please check if this works now.
However, I have no info file yet, so this argument cannot be used. If you want to rename the standard gist output file, please use out. Plus, the prefix is also not yet available, this will be changed in order to fit the GIST implementation in cpptraj.
In general, a set of available commands is supplied when typing `help gigist`.

**Comment by acruzpr** [comment]
Hi, 
Thanks for your fast response.

I will try this fix and I will let you know!
Thanks!

**Comment by acruzpr** [comment]
Thanks! It works.
I will do some tests and I will let you know...

**Comment by jokr91** [comment]
Thanks for the help, I will then incorporate the fixes in master.
If you find anything else, please just open another issue then.

**Comment by acruzpr** [comment]
Will do!
Thanks!
